apiVersion: v1
kind: Service
metadata:
  name: ngix-svc
  labels:
    app: nginx
spec: 
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 80
  selector:
    matchLables:
      app: nginx
      